name: Deploy to GitHub Pages
    push:
      branches:
        - main
    workflow_dispatch: {}

jobs:
    deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: '18'

        - name: Install
          run: npm ci || npm install

        - name: Build web
          run: npx expo export --platform web --output-dir dist --public-url https://kymtooo.github.io/Flowcus/

        - name: Disable Jekyll
          run: touch dist/.nojekyll

        - name: SPA fallback for GitHub Pages
          run: cp dist/index.html dist/404.html

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: dist
            force_orphan: true
